### PR TITLE
Added location of  settings page to README

### PR DESCRIPTION
**Pull request by natkuhn**
Looking at existing documentation, it was not clear that there is a GUI way to change settings. I clarified this.

I was also thinking that for consistency, the title under Extensions should either be "VS Code Printing" (name of the extension) or "Print" (the name under which the commands are filed).

I am a noob, but if you are interested in one  or the other of those changes I could try to add to this PR, or create a new one.

Thanks!

### CODE REVIEW

**Comment by natkuhn** [comment]
Thanks, @PeterWone! This is my first pull request, so, as small as it is, it is a nice moment for me!

I will do another PR for the edit you suggested.

What do you think about the idea of changing "Printing" in the Extensions settings to either "VS Code Printing" or "Print"?

I may suggest some other edits to coordinate the README and the manual.md a little more closely.

**Comment by PeterWone** [comment]
The case against "Printing” boils down to


  1.  What if Microsoft provides baked-in support for printing?
  2.  What if someone else provides a printing extension?

If (1) happens everyone will remove VS Code Printing and it won’t matter. (2) seems unlikely. VS Code Printing works very well so there is no motivation. On that basis I rather arrogantly decided to co-opt “Printing”.

Can you see a down side?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by natkuhn** [comment]
Hi Peter, as I thought about this I came around to this point of view.

You might consider changing the command names to "Printing: Print" (which is a little better than "Print: Print" anyway, I think) and "Printing: Browse for..."

As for (2), I agree that your extension is great!

**Comment by PeterWone** [comment]
"Printer:Print" -- Yes, you may be right. But that's minor grooming. I guess it's a good thing if that's the most important change we can think of.

**Pull request merged**
